services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    env_file: .env
    restart: always
    expose:
      - "3306"
    networks:
      - inception_net
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    expose:
      - "9000"
    restart : always

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception_net
    depends_on:
      - wordpress
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    ports:
      - target: 443
        published: 443
    restart: always

networks:
  inception_net:
    name : inception_net
    driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/omansour/data/wordpress
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/omansour/data/mariadb
