services:
  mariadb:
    container_name: mariadb
    image: mariadb:v1
    build: requirements/mariadb
    env_file: .env
    expose:
      - "3306"
    networks:
      - inception_net
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  wordpress:
    container_name: wordpress
    image: wordpress:v1
    build: requirements/wordpress
    env_file: .env
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception_net
    depends_on:
      - mariadb
    restart : always

  nginx:
    container_name: nginx
    image: nginx:v1
    build: requirements/nginx
    env_file: .env
    ports:
      - target: 443
        published: 443
    networks:
      - inception_net
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: always

networks:
  inception_net:
    name : inception_net
    driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/omansour/data/wordpress
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/omansour/data/mariadb
