version: '3.7'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb
    env_file: .env
    restart: always
    expose:
      - "3306"
    networks:
      - net_inception
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - net_inception
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    expose:
      - "9000"
    restart : always

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - net_inception
    depends_on:
      - wordpress
    build: requirements/nginx
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    ports:
      - target: 443
        published: 443
    restart: always

networks:
  net_inception:
    driver: bridge

volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/omansour/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none' 
            o: 'bind'
            device: '/home/omansour/data/mariadb'
